import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexDirection: 'column',
    marginBottom: 100,
  },
  title: {
    fontSize: 14,
    marginTop: 10,
    color: '#222',
  },
  subTitle: {
    color: '#222',
    fontSize: 20,
    textShadow: '0 0 50px rgba(0,0,0,1)',
  },
  info: {
    background: theme.palette.primary.main,
    color: '#fff',
    padding: 20,
    width: '100%',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
  },
  descriptionTitle: { fontSize: 30, marginTop: 20 },
  description: {
    fontSize: 16,
    marginTop: 20,
    paddingRight: 20,
    boxSizing: 'border-box',
  },
  wrapperOne: {
    width: '100%',
    height: 500,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  wrapperTwo: {
    backgroundSize: 'cover',
    backgroundPosition: 'center center',
    width: '100%',
    height: 300,
  },
  inset: {
    width: 120,
    height: 120,
    border: '3px solid #fff',
    borderRadius: 20,
    background: theme.palette.primary.main,
    boxShadow: '0 0 30px rgba(0,0,0,0.2)',
    marginTop: -50,
    backgroundSize: 'cover',
    backgroundPosition: 'center center',
  },
  wrapperThree: {
    maxWidth: 500,
    zIndex: 3,
  },
  wrapperFour: {
    textAlign: 'center',
    color: 'rgba(0,0,0,0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: 40,
  },
  wrapperFive: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  cover: {
    width: '100%',
    height: 500,
    position: 'absolute',
  },
  column: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  columnWrapper: {
    maxWidth: 600,
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '1px dotted #ccc',
    paddingBottom: 40,
  },
}));
