import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexDirection: 'column',
    marginBottom: 100,
  },
  title: {
    fontSize: 14,
    marginTop: 20,
    marginBottom: 20,
  },
  subTitle: {
    color: theme.palette.primary.light,
    fontSize: 20,
  },
  info: {
    background: theme.palette.primary.main,
    color: '#fff',
    padding: 20,
    width: '100%',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
  },
  descriptionTitle: { fontSize: 30, marginTop: 20 },
  description: {
    fontSize: 16,
    marginTop: 20,
    paddingRight: 20,
    boxSizing: 'border-box',
  },
  wrapperOne: {
    width: '100%',
    height: 500,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  wrapperTwo: {
    backgroundSize: 'cover',
    backgroundPosition: 'center center',
    width: '100%',
    height: 500,
    position: 'absolute',
    filter: 'brightness(0.8) grayscale(70%)',
  },
  wrapperThree: {
    padding: 30,
    maxWidth: 500,
    background: 'rgba(38,31,71,0.5)',
    filter: 'brightness(1)',
  },
  wrapperFour: {
    textAlign: 'center',
    color: '#fff',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  wrapperFive: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  cover: {
    background: 'rgba(87,73,158,0.6)',
    width: '100%',
    height: 500,
    position: 'absolute',
  },
  column: {
    width: '50%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  columnWrapper: {
    maxWidth: 900,
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '1px dotted #ccc',
    paddingBottom: 40,
  },
}));
