import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    width: 180,
    height: 200,
    paddingTop: 30,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    cursor: 'pointer',
    marginLeft: 6,
    marginRight: 6,
  },
  avatar: {
    backgroundColor: '#fff',

    minWidth: 84,
    maxWidth: 84,
    minHeight: 84,
    maxHeight: 84,
    marginBottom: -42,
    border: '3px solid #fff',
    borderRadius: '50%',
    backgroundSize: 'cover',
    position: 'relative',
    zIndex: 2,
    boxShadow: '3px 3px 5px rgba(0,0,0,0.2)',
  },
  bgImg: {
    width: 180,
    height: 120,
    backgroundSize: 'cover',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'column',
    padding: 3,
    boxShadow: '3px 3px 5px rgba(0,0,0,0.2)',
  },
  details: {
    background: '#fff',
    padding: 5,
    boxSizing: 'border-box',
    borderRadius: '0 0 8px 8px',
    width: '100%',
    textAlign: 'center',
  },
}));
