import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  card: {
    width: '100%',
    marginBottom: 5,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
    backgroundColor: '#fff',
    height: 80,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  count: {
    background: theme.palette.primary.main,
    borderRadius: '50%',
    minHeight: 16,
    maxHeight: 16,
    minWidth: 16,
    maxWidth: 16,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 36,
    marginRight: 5,
    marginTop: -30,
    color: '#fff',
    border: '2px solid #fff',
    fontSize: 10,
    zIndex: 2,
  },
  dull: { color: theme.palette.primary.main },
  red: { color: theme.palette.primary.main },
  green: { color: theme.palette.secondary.main },
  profileThumb: {
    backgroundColor: '#ddd',
    backgroundSize: 'cover',
    border: '2px solid #ddd',
    minWidth: 40,
    maxWidth: 40,
    minHeight: 40,
    maxHeight: 40,
    marginRight: 5,
    marginLeft: -25,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    filter: 'brightness(50%)',
  },
  profileThumbNotification: {
    border: `2px solid ${theme.palette.secondary.main}`,
    filter: 'brightness(100%)',
  },
  countsStyle: {
    position: 'absolute',
    top: -5,
    left: -5,
    maxHeight: 20,
    minHeight: 20,
    maxWidth: 20,
    minWidth: 20,
    borderRadius: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.palette.secondary.main,
    color: '#222',
    zIndex: 10,
  },
  declined: {
    backgroundColor: '#000',
    opacity: '0.5',
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gameImg: {
    width: 180,
    height: '100%',
    background: theme.palette.primary.main,
  },
  cardContentCenter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexWrap: 'nowrap',
    width: '100%',
    height: '100%',
    paddingBottom: 20,
  },
  cardSummary: { overflow: 'hidden' },
  cardSummaryNeutral: {
    color: theme.palette.primary.main,
  },
  cardSummaryWarning: { color: theme.palette.primary.main },
  cardSummaryGood: { color: theme.palette.secondary.main },
  cardSummaryAmber: { color: theme.palette.warning.main },
  cardEmpty: {
    width: '30%',
    margin: '20px auto 20px 0',
    minWidth: 300,
    background: '#ddd',
  },

  cardMedia: { borderRadius: '50%', border: '10px solid #ddd', width: 140 },
  cardLink: {
    lineHeight: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center ',
    textDecoration: 'none',
    marginRight: 5,
    marginLeft: 5,
  },
  flexCenter: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center ',
  },
  title: {
    fontSize: 14,
  },
  buttonCentre: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textDecoration: 'none',
  },
}));
