import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  messageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  messageWrapperMobile: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  profileWrapperFeatured: {
    minWidth: 120,
    maxWidth: 120,
    minHeight: 120,
    maxHeight: 120,
    borderRadius: 20,

    marginBottom: 20,
    border: '4px solid #fff',
    boxShadow: '10px 10px 20px rgba(0,0,0,0.4)',
  },
  postHeader: {
    bottom: 0,
    background: '#fff',
    borderBottom: 'none',
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 10,
    width: 350,
    height: '100%',
    boxSizing: 'border-box',
  },
  featuredText: {
    fontSize: 16,
    marginBottom: 20,
    color: '#fff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottom: '1px dotted #aaa',
    width: '100%',
    paddingBottom: 5,
  },
  postHeaderText: {
    color: '#222',
    width: '100%',
    height: '100%',
    alignSelf: 'flex-start',

    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    fontSize: 24,
  },
  postImage: {
    position: 'relative',
    width: '100%',
    backgroundSize: 'cover',
    backgroundPosition: 'center center',
    height: 400,
  },
  card: {
    width: '100%',
    borderRadius: 0,
  },
  rowWrapper: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  wrapperOne: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    width: '100%',
    height: '100%',
  },
  messageDetails: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: '100%',
    height: '100%',
  },
  messageButton: {
    width: '100%',
    lineHeight: 0.6,
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  profileWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
}));
