import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  messageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  messageWrapperMobile: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  postHeader: {
    color: theme.palette.primary.main,
    position: 'absolute',
    bottom: 0,
    background: 'rgba(255,255,255,0.9)',
    borderTop: '1px solid #ddd',
    padding: 30,
    paddingBottom: 10,
    paddingTop: 25,
    width: 300,
    marginLeft: 30,
    boxSizing: 'border-box',
    boxShadow: '0 0 10px rgba(0,0,0,0.2)',
  },
  featuredText: {
    fontSize: 20,
    marginTop: -50,
    color: '#fff',
    background: theme.palette.primary.main,
    borderRadius: 0,
    padding: 10,
    boxShadow: '10px 10px 20px rgba(0,0,0,0.2)',
  },
  postHeaderText: { color: '#222', alignSelf: 'flex-start', marginTop: 20 },
  postImage: {
    position: 'relative',
    width: '100%',
    backgroundSize: 'cover',
    backgroundPosition: 'top center',
    height: 400,
  },
  card: {
    width: '100%',
    borderRadius: 0,
  },
  rowWrapper: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  wrapperOne: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    width: '100%',
    height: '100%',
  },
  messageDetails: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: '100%',
    height: '100%',
  },
  messageButton: {
    width: '100%',
    lineHeight: 0.6,
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  profileWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
}));
