export const initialState = {
  name: '',
  img: '',
  genre: '',
  summary: '',
  scope: '',
  mechanics: '',
  timeframe: '',
  extra: '',
  budget: '',
  funded: false,
  speculative: false,
  inLieu: false,
  keywords: [],
  location: '',
  showreel: '',
  type: 'job',
  creativeSummary: '',
  termsAccepted: false,
  _id: 'new',
  gameId: '',
  submitted: '',
};
