import { makeStyles } from '@material-ui/core/styles';
export const useStyles = makeStyles((theme) => ({
  creativeCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    width: '100%',
    position: 'relative',
  },
  skillName: {
    color: '#fff',
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textTransform: 'uppercase',
  },
  shareLink: {
    color: theme.palette.primary.main,
    fontSize: 12,
  },
  background: {
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundColor: theme.palette.primary.main,
    backgroundPosition: 'center center',
    height: 320,
    width: '100%',
    position: 'relative',
    cursor: 'pointer',
  },
  imageThumb: {
    height: '100%',
    width: 100,
    margin: 2,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    opacity: 0.8,
    '&:hover': { opacity: 1 },
  },
  socialImg: { width: '100%', height: '100%' },
  social: {
    textDecoration: 'none',
    maxHeight: 20,
    minHeight: 20,
    maxWidth: 20,
    minWidth: 20,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '1px solid #fff',
    margin: 5,
    boxShadow: '2px 2px 3px rgba(0,0,0,0.2)',
    background: '#fff',
  },
  website: {
    textDecoration: 'underline',
    color: '#222',
    textAlign: 'center',
    fontSize: 12,
    marginRight: 10,
  },
  email: {
    textDecoration: 'none',
    width: '100%',
    fontSize: 12,
    color: theme.palette.primary.main,
  },
  divider: {
    width: '60%',
    borderTop: '1px solid #ddd',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingBottom: 6,
  },
  summary: {
    paddingBottom: 6,
    marginBottom: 10,
  },
  types: { fontStyle: 'italic', fontSize: 12 },
  catTitle: { color: '#fff', marginLeft: 5, marginRight: 5 },
}));
