import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  messageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '50%',
  },
  messageWrapperMobile: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  postHeader: {
    color: '#fff',
    position: 'absolute',
    bottom: 0,
    background: 'rgba(0,0,0,0.7)',
    padding: 10,
    width: '100%',
    boxSizing: 'border-box',
  },
  postImage: {
    position: 'relative',
    width: '100%',
    backgroundSize: 'cover',
    backgroundPosition: 'top center',
    height: 200,
  },
  card: {
    width: '100%',
    margin: '15px 0 0 0',
    boxShadow: '10px 10px 15px rgba(0,0,0,0.2)',
  },
  rowWrapper: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  wrapperOne: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    width: '100%',
    height: '100%',
  },
  messageDetails: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: '100%',
    height: '100%',
  },
  messageButton: {
    width: '100%',
    lineHeight: 0.6,
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  profileWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
}));
