import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
  inputWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    paddingBottom: 30,
    boxSizing: 'border-box',
    borderBottom: '1px solid #ddd',
  },
  inputWrapperMobile: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'column',
    flexWrap: 'wrap',
  },
  actionInputWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'column',
    width: '100%',
  },
  avatarWrapper: {
    position: 'relative',
    width: 160,
    minWidth: 160,
    maxWidth: 160,
    minHeight: 160,
    maxHeight: 160,
    height: 160,
    padding: 0,
    marginLeft: 40,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundPosition: 'center center',
    backgroundSize: 'cover',
    border: '1px dotted #ccc',
    borderRadius: 5,
    boxSizing: 'border-box',
  },
  inputFocus: { background: '#ddd' },
  avatarWrapperMobile: {
    marginRight: 0,
  },
});
